# Generated by Django 3.2.25 on 2026-03-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('materi', 'Kuis Materi'), ('final', 'Final Test')], max_length=10)),
                ('pertanyaan', models.TextField()),
                ('pilihan_a', models.CharField(max_length=255)),
                ('pilihan_b', models.CharField(max_length=255)),
                ('pilihan_c', models.CharField(max_length=255)),
                ('pilihan_d', models.CharField(max_length=255)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('bobot', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HalamanMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('konten', models.TextField()),
                ('konten_html', models.TextField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peserta', models.ManyToManyField(blank=True, related_name='kursus_diikuti', through='kitajalan.Enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('konten', models.TextField()),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='kitajalan.kursus')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='SesiKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('materi', 'Kuis Materi'), ('final', 'Final Test')], max_length=10)),
                ('status', models.CharField(choices=[('mulai', 'Mulai'), ('sedang', 'Sedang Mengerjakan'), ('selesai', 'Selesai'), ('lulus', 'Lulus'), ('gagal', 'Gagal')], default='mulai', max_length=10)),
                ('percobaan_ke', models.IntegerField(default=1)),
                ('total_soal', models.IntegerField(default=5)),
                ('jawaban_benar', models.IntegerField(default=0)),
                ('nilai', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus')),
                ('materi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressHalaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('halaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.halamanmateri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaPembelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tipe', models.CharField(choices=[('video', 'Video'), ('gambar', 'Gambar'), ('file', 'File Dokumen')], max_length=10)),
                ('file', models.FileField(help_text='Upload video, gambar, atau dokumen', upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JawabanKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_user', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_benar', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='kitajalan.sesikuis')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.banksoal')),
            ],
        ),
        migrations.AddField(
            model_name='halamanmateri',
            name='materi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaman', to='kitajalan.materi'),
        ),
        migrations.CreateModel(
            name='HalamanBlok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('image', 'Image'), ('video', 'Video'), ('local_image', 'Gambar Lokal'), ('local_video', 'Video Lokal')], max_length=20)),
                ('konten', models.TextField(blank=True, null=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('halaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blok', to='kitajalan.halamanmateri')),
            ],
            options={
                'db_table': 'kitajalan_halamanblok',
                'ordering': ['urutan'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='kursus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banksoal',
            name='kursus',
            field=models.ForeignKey(help_text='Kursus tempat soal ini digunakan', on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus'),
        ),
        migrations.AddField(
            model_name='banksoal',
            name='materi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika untuk final test', null=True, on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi'),
        ),
        migrations.CreateModel(
            name='ProgressMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('is_quiz_passed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'materi')},
            },
        ),
        migrations.CreateModel(
            name='ProgressKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudah_lulus', models.BooleanField(default=False)),
                ('nilai_tertinggi', models.IntegerField(default=0)),
                ('total_percobaan', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus')),
                ('materi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'materi', 'kursus')},
            },
        ),
        migrations.AddConstraint(
            model_name='progresshalaman',
            constraint=models.UniqueConstraint(fields=('user', 'halaman'), name='unique_progress_halaman'),
        ),
        migrations.AddConstraint(
            model_name='materi',
            constraint=models.UniqueConstraint(fields=('kursus', 'slug'), name='unique_slug_per_kursus'),
        ),
        migrations.AlterUniqueTogether(
            name='jawabankuis',
            unique_together={('sesi', 'soal')},
        ),
        migrations.AddConstraint(
            model_name='halamanmateri',
            constraint=models.UniqueConstraint(fields=('materi', 'slug'), name='unique_slug_per_materi'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'kursus'), name='unique_user_kursus'),
        ),
    ]
