# Generated by Django 3.2.25 on 2026-03-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitajalan', '0002_add_media_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesikuis',
            name='batas_waktu',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='sesikuis',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesikuis',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesikuis',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediapembelajaran',
            name='file',
            field=models.FileField(help_text='Upload video, gambar, atau dokumen', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mediapembelajaran',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sesikuis',
            name='status',
            field=models.CharField(choices=[('mulai', 'Mulai'), ('sedang', 'Sedang Mengerjakan'), ('selesai', 'Selesai'), ('lulus', 'Lulus'), ('gagal', 'Gagal'), ('waktu_habis', 'Waktu Habis')], default='mulai', max_length=15),
        ),
        migrations.AlterModelTable(
            name='halamanblok',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mediapembelajaran',
            table=None,
        ),
    ]
