# Generated by Django 3.2.25 on 2026-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitajalan', '0003_auto_20260308_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(help_text='Pertanyaan utama', max_length=255)),
                ('kata_kunci', models.CharField(help_text='Pisahkan dengan koma. Contoh: daftar, registrasi', max_length=255)),
                ('jawaban', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Prioritas jawaban (angka lebih kecil lebih prioritas)')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diupdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Chatbot',
                'verbose_name_plural': 'FAQ Chatbot',
                'ordering': ['urutan', 'pertanyaan'],
            },
        ),
    ]
