# Generated by Django 3.2.25 on 2026-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitajalan', '0004_faqchatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('active', 'Aktif'), ('completed', 'Selesai')], default='pending', max_length=20),
        ),
    ]
