# Generated by Django 3.2.25 on 2026-03-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitajalan', '0005_enrollment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresskuis',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progressmateri',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='progresskuis',
            constraint=models.UniqueConstraint(fields=('user', 'materi'), name='unique_progress_kuis_materi'),
        ),
        migrations.AddConstraint(
            model_name='progressmateri',
            constraint=models.UniqueConstraint(fields=('user', 'materi'), name='unique_progress_materi'),
        ),
    ]
