# Generated by Django 3.2.25 on 2026-02-09 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(help_text='Isi materi dalam Markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('konten', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='kitajalan.kursus')),
            ],
            options={
                'ordering': ['urutan'],
                'unique_together': {('kursus', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HalamanMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('konten', models.TextField()),
                ('konten_html', models.TextField(blank=True, null=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaman', to='kitajalan.materi')),
            ],
            options={
                'ordering': ['urutan'],
                'unique_together': {('materi', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HalamanBlok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('code', 'Code')], max_length=20)),
                ('urutan', models.PositiveIntegerField()),
                ('konten', models.TextField()),
                ('halaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blok', to='kitajalan.halamanmateri')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'materi')},
            },
        ),
        migrations.CreateModel(
            name='ProgressHalaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('halaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.halamanmateri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'halaman')},
            },
        ),
    ]
