# Generated by Django 3.2.25 on 2026-02-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitajalan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halamanmateri',
            name='konten_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kursus')},
            },
        ),
    ]
