# Generated by Django 3.2.25 on 2026-02-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitajalan', '0002_auto_20260212_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AlterModelOptions(
            name='halamanblok',
            options={'ordering': ['urutan']},
        ),
        migrations.AlterModelOptions(
            name='kursus',
            options={'ordering': ['nama']},
        ),
        migrations.AddField(
            model_name='kursus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kursus',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kursus',
            name='peserta',
            field=models.ManyToManyField(blank=True, related_name='kursus_diikuti', through='kitajalan.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='halamanmateri',
            name='konten_html',
            field=models.TextField(blank=True, default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halamanmateri',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='kursus',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='halamanmateri',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materi',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progresshalaman',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progressmateri',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'kursus'), name='unique_user_kursus'),
        ),
        migrations.AddConstraint(
            model_name='halamanmateri',
            constraint=models.UniqueConstraint(fields=('materi', 'slug'), name='unique_slug_per_materi'),
        ),
        migrations.AddConstraint(
            model_name='materi',
            constraint=models.UniqueConstraint(fields=('kursus', 'slug'), name='unique_slug_per_kursus'),
        ),
        migrations.AddConstraint(
            model_name='progresshalaman',
            constraint=models.UniqueConstraint(fields=('user', 'halaman'), name='unique_progress_halaman'),
        ),
        migrations.AddConstraint(
            model_name='progressmateri',
            constraint=models.UniqueConstraint(fields=('user', 'materi'), name='unique_progress_materi'),
        ),
    ]
