# Generated by Django 3.2.25 on 2026-02-14 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitajalan', '0003_auto_20260213_2248'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='progressmateri',
            name='unique_progress_materi',
        ),
        migrations.AlterUniqueTogether(
            name='progressmateri',
            unique_together={('user', 'materi')},
        ),
        migrations.AddConstraint(
            model_name='halamanblok',
            constraint=models.UniqueConstraint(fields=('halaman', 'urutan'), name='unique_urutan_per_halaman'),
        ),
    ]
