# Generated by Django 3.2.25 on 2026-03-04 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitajalan', '0004_auto_20260214_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('materi', 'Kuis Materi'), ('final', 'Final Test')], max_length=10)),
                ('pertanyaan', models.TextField()),
                ('pilihan_a', models.CharField(max_length=255)),
                ('pilihan_b', models.CharField(max_length=255)),
                ('pilihan_c', models.CharField(max_length=255)),
                ('pilihan_d', models.CharField(max_length=255)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('bobot', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JawabanKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_user', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_benar', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudah_lulus', models.BooleanField(default=False)),
                ('nilai_tertinggi', models.IntegerField(default=0)),
                ('total_percobaan', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesiKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('materi', 'Kuis Materi'), ('final', 'Final Test')], max_length=10)),
                ('status', models.CharField(choices=[('mulai', 'Mulai'), ('sedang', 'Sedang Mengerjakan'), ('selesai', 'Selesai'), ('lulus', 'Lulus'), ('gagal', 'Gagal')], default='mulai', max_length=10)),
                ('percobaan_ke', models.IntegerField(default=1)),
                ('total_soal', models.IntegerField(default=5)),
                ('jawaban_benar', models.IntegerField(default=0)),
                ('nilai', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='halamanblok',
            name='unique_urutan_per_halaman',
        ),
        migrations.AlterField(
            model_name='halamanblok',
            name='konten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='halamanblok',
            name='tipe',
            field=models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
        migrations.AlterField(
            model_name='halamanblok',
            name='urutan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesikuis',
            name='kursus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus'),
        ),
        migrations.AddField(
            model_name='sesikuis',
            name='materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi'),
        ),
        migrations.AddField(
            model_name='sesikuis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progresskuis',
            name='kursus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus'),
        ),
        migrations.AddField(
            model_name='progresskuis',
            name='materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi'),
        ),
        migrations.AddField(
            model_name='progresskuis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabankuis',
            name='sesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='kitajalan.sesikuis'),
        ),
        migrations.AddField(
            model_name='jawabankuis',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitajalan.banksoal'),
        ),
        migrations.AddField(
            model_name='banksoal',
            name='kursus',
            field=models.ForeignKey(help_text='Kursus tempat soal ini digunakan', on_delete=django.db.models.deletion.CASCADE, to='kitajalan.kursus'),
        ),
        migrations.AddField(
            model_name='banksoal',
            name='materi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika untuk final test', null=True, on_delete=django.db.models.deletion.CASCADE, to='kitajalan.materi'),
        ),
        migrations.AlterUniqueTogether(
            name='progresskuis',
            unique_together={('user', 'materi', 'kursus')},
        ),
        migrations.AlterUniqueTogether(
            name='jawabankuis',
            unique_together={('sesi', 'soal')},
        ),
    ]
