# Generated by Django 3.2.25 on 2026-03-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitajalan', '0005_auto_20260304_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressmateri',
            name='is_quiz_passed',
            field=models.BooleanField(default=False),
        ),
    ]
